### ISSUE TITLE
Update HousingDB data - new schema July 2020

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-cp-platform#19]
**NOTE: Only draft data is available right now, but we should still go ahead and make the updated for the new schema. Final data will be provided in Sprint Q.**

The latest HousingDB in the new schema can be found here: https://github.com/NYCPlanning/db-developments#file-download

Schema changes: the [main table tab of this Excel spreadsheet](https://nyco365.sharepoint.com/:x:/s/NYCPLANNING/itd/edm/EUFKhsrhInBCuaIvIkwMr6wBgmjOVMugn6Dk_-1QwpYTBA?e=o9PUd9&wdLOR=c3EBF5FB8-232D-E049-85B6-58B376B2AE4F) maps old fields to new fields and flags which fields will be shared with the agency / public.

**Tasks Involved**
Refer to the data update playbook: https://docs.google.com/document/d/1txHqKW-PCm3XIHrzR4xfJVhXvA3nOaf7r1v6XmDekbA/edit

- [x] Plugin new tables names for housing files app/config/db_tables.js
- [x] Update all field references to use the new field names
- [x] Update the development status filter to reflect the new [values](https://github.com/NYCPlanning/db-developments/wiki/20Q2-Attribute-mapping#job_status) ![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/458afd92-558d-4d89-95cc-bffcf590d1d0)
- [x] Three certificate of occupancy (co) fields will no longer be provided. They are currently displayed on the project profile. That section of the profile will need to be deleted.
  - co_latest_effectivedate
  - co_latest_certtype
  - co_latest_units
- [x] Add Application filing date
- [x] Update header to Dept of Buildings....
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/0a71bda5-e579-4d5b-ad10-a44ee7f61237)
